In [1]:
import tensorflow as tf
from numpy.random import RandomState

#### 1. 定义神经网络的相关参数和变量。

In [2]:
batch_size = 8
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_ = tf.placeholder(tf.float32, shape=(None, 1), name='y-input')
w1= tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#### 2. 设置自定义的损失函数。
### [MarkDown math](https://www.zybuluo.com/codeep/note/163962)
### loss定义：
$$loss= \sum_{i=1}^n f(y,y^{'}), f(y,y^{'})= \begin{cases} a*(y-y^{'}), & \text {if $y>y^{'}$} \\ b*(y^{'}-y), & \text {if $y<y^{'}$} \end{cases}$$

In [3]:
# 定义损失函数使得预测少了的损失大，于是模型应该偏向多的方向预测。
loss_less = 10 # less then loss $10
loss_more = 1 # more then loss $1
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

#### 3. 生成模拟数据集。

In [4]:
rdm = RandomState(1) # seed=1
X = rdm.rand(128,2)
# rand num:(-0.05~0.05)
Y = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

#### 4. 训练模型。

In [5]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print sess.run(w1), "\n"
    print "Final w1 is: \n", sess.run(w1)

After 0 training step(s), w1 is: 
[[-0.81031823]
 [ 1.4855988 ]] 

After 1000 training step(s), w1 is: 
[[0.01247114]
 [2.138545  ]] 

After 2000 training step(s), w1 is: 
[[0.45567423]
 [2.1706069 ]] 

After 3000 training step(s), w1 is: 
[[0.69968736]
 [1.846531  ]] 

After 4000 training step(s), w1 is: 
[[0.8988668]
 [1.2973604]] 

Final w1 is: 
[[1.0193471]
 [1.0428091]]


#### 5. 重新定义损失函数，使得预测多了的损失大，于是模型应该偏向少的方向预测。

In [6]:
loss_less = 1 # less then loss $1
loss_more = 10 # more then loss $10
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print sess.run(w1), "\n"
    print "Final w1 is: \n", sess.run(w1)

After 0 training step(s), w1 is: 
[[-0.8123182]
 [ 1.4835987]] 

After 1000 training step(s), w1 is: 
[[0.18643522]
 [1.0739335 ]] 

After 2000 training step(s), w1 is: 
[[0.95444274]
 [0.9808863 ]] 

After 3000 training step(s), w1 is: 
[[0.9557403]
 [0.9806634]] 

After 4000 training step(s), w1 is: 
[[0.95466024]
 [0.9813524 ]] 

Final w1 is: 
[[0.9556111]
 [0.9810191]]


#### 6. 定义损失函数为MSE。
### MSE 定义：
$$mse(y,y^{'})=\frac{1}{n} \sum_{i=1}^n(y-y^{'})^2$$

In [7]:
loss = tf.losses.mean_squared_error(y, y_)
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print sess.run(w1), "\n"
    print "Final w1 is: \n", sess.run(w1)
    sess.close()

After 0 training step(s), w1 is: 
[[-0.81031823]
 [ 1.4855988 ]] 

After 1000 training step(s), w1 is: 
[[-0.1333761]
 [ 1.8130922]] 

After 2000 training step(s), w1 is: 
[[0.32190308]
 [1.5246348 ]] 

After 3000 training step(s), w1 is: 
[[0.6785022]
 [1.2529727]] 

After 4000 training step(s), w1 is: 
[[0.8947401]
 [1.0859822]] 

Final w1 is: 
[[0.9743756]
 [1.0243336]]
